---
# Name of the playbook
- name: Our first Ansible playbook
  # List of hosts or host group to run against
  hosts: localhost
  # Toggle to run with root privileges
  become: true

  # Variables we define to use within this playbook
  vars:
    # Password to use when running command as root
    ansible_become_password: "@rista123"

  # List of tasks to be executed
  tasks:
    # Name of one task
    - name: Install some packages
      # Action of this task - in this case, the apt package manager module
      apt:
        # This is an Ansible looping technique
        # {{ item }} is an iterator variable which will take the value of each item in the list from with_items
        name: "{{ item }}"
        state: present
      # List of the packages to be installed
      with_items:
        - pandoc
        - jq
